parallel-jobs = 1
patches-version = "latest"
enable-magisk-update = true
remove-rv-integrations-checks = true

[YouTube-Advanced]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Advanced]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
