patches-version = "dev"
enable-magisk-update = false
parallel-jobs = 1
remove-rv-integrations-checks = true

[YouTube-ReVanced]
enabled = false
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-ReVanced]
enabled = false
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Google-Photos-ReVanced]
enabled = false
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[Google-Recorder-ReVanced]
enabled = false 
build-mode = "both"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"

[Proton-Mail-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[Proton-VPN-ReVanced]
enabled = false
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"

[Samsung-Radio-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[Lightroom-ReVanced]
enabled = false
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[Duolingo-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"
archive-dlurl = "https://archive.org/download/geologically/apks/com.duolingo"

[Gboard-ReVanced-Privacy]
enabled = true
app-name = "Gboard"
rv-brand = "ReVanced-Privacy"
build-mode = "both"
arch = "both"
patches-source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
# archive-dlurl = ""

[Reddit-ReVanced-Privacy]
enabled = true 
app-name = "Reddit"
rv-brand = "ReVanced-Privacy"
patches-source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[YouTube-ReVanced-Extended]
enabled = false
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-ReVanced-Extended]
enabled = false
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[YouTube-ReVanced-Advanced]
enabled = false
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Advanced]
enabled = false
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Twitter-Piko]
enabled = false 
app-name = "Twitter"
arch = "both"
rv-brand = "Piko"
patches-source = "crimera/piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
build-mode = "both"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[YouTube-Morphe-Extended]
enabled = true
app-name = "YouTube"
build-mode = "both"
rv-brand = "Morphe-Extended"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Morphe-Extended]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "Morphe-Extended"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe-Extended]
enabled = true 
app-name = "Reddit"
rv-brand = "Morphe-Extended"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

