parallel-jobs = 1
patches-version = "dev"
enable-magisk-update = false
remove-rv-integrations-checks = true

[proton-mail-revanced]
enabled = true
app-name = "proton-mail"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[samsung-radio-revanced]
enabled = true
app-name = "samsung-radio"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[lightroom-revanced]
enabled = true
app-name = "lightroom"
rv-brand = "revanced"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[duolingo-revanced]
enabled = true
app-name = "duolingo"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"
archive-dlurl = "https://archive.org/download/geologically/apks/com.duolingo"

[twitch-revanced]
enabled = true
app-name = "twitch"
rv-brand = "revanced"
version = "25.3.0"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[twitter-revanced]
enabled = true
app-name = "twitter"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[tiktok-revanced]
enabled = true
app-name = "tiktok"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"

[youtube-revanced]
enabled = true
app-name = "youtube"
rv-brand = "revanced"
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-revanced]
enabled = true
app-name = "youtube-music"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[google-photos-revanced]
enabled = true
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[google-recorder-revanced]
enabled = true 
app-name = "google-recorder"
rv-brand = "revanced"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"

[proton-vpn-revanced]
enabled = true
app-name = "proton-vpn"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"

[reddit-jkennethcarino]
enabled = true 
app-name = "reddit"
rv-brand = "jkennethcarino"
patches-source = "jkennethcarino/privacy-revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[twitter-piko]
enabled = true 
app-name = "twitter"
rv-brand = "piko"
arch = "both"
patches-source = "crimera/piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[youtube-morphe]
enabled = true
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"




