parallel-jobs = 1
patches-version = "dev"
enable-magisk-update = true
remove-rv-integrations-checks = true

[Gboard-ReVanced-Privacy]
enabled = false
app-name = "Gboard"
rv-brand = "ReVanced-Privacy"
build-mode = "both"
arch = "both"
patches-source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
# archive-dlurl = ""

[Reddit-ReVanced-Privacy]
enabled = false 
app-name = "Reddit"
rv-brand = "ReVanced-Privacy"
patches-source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[Reddit-Morphe-Extended]
enabled = true 
app-name = "Reddit"
rv-brand = "Morphe-Extended"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
cli-version = "dev"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
