parallel-jobs = 1
patches-version = "dev"
enable-magisk-update = false
remove-rv-integrations-checks = true

[Proton-Mail-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[Samsung-Radio-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[Lightroom-ReVanced]
enabled = false
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[Duolingo-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"
archive-dlurl = "https://archive.org/download/geologically/apks/com.duolingo"

[Twitch-ReVanced]
enabled = false 
version = "25.3.0"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[Twitter-ReVanced]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[TikTok-ReVanced]
enabled = true 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"




