parallel-jobs = 1
patches-version = "latest"
enable-magisk-update = true
remove-rv-integrations-checks = true

[YouTube-Morphe]
enabled = true
app-name = "YouTube"
build-mode = "both"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Morphe]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
