enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

[YouTube]
enabled = false
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music]
enabled = false
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Google-Photos]
enabled = false
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# # archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[Google-Recorder]
enabled = false 
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"

[Proton-Mail]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
# archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[Proton-VPN]
enabled = false
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"

[Samsung-Radio]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[Lightroom]
enabled = false
arch = "arm64-v8a"
version = "auto"
patches-source = "ReVanced/revanced-patches"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Extended]
enabled = false
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[YouTube-Advanced]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Advanced]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[YouTube-LisoUseInAIKyrios]
enabled = false
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-LisoUseInAIKyrios"
cli-source = "LisoUseInAIKyrios/revanced-cli"
patches-source = "LisoUseInAIKyrios/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-LisoUseInAIKyrios]
enabled = false
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-LisoUseInAIKyrios"
cli-source = "LisoUseInAIKyrios/revanced-cli"
patches-source = "LisoUseInAIKyrios/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Twitter-Piko]
enabled = false 
app-name = "Twitter"
arch = "both"
rv-brand = "ReVanced-Piko"
patches-source = "crimera/piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
