parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[Music]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Photos]
enabled = true
app-name = "Photos"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"

[Duolingo]
enabled = false 
app-name = "Duolingo"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"

[Twitch]
enabled = false 
app-name = "Twitch"
build-mode = "apk"
arch = "all"
version = "25.3.0"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"

[ProtonMail]
enabled = true 
app-name = "ProtonMail"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"

[SamsungRadio]
enabled = true
app-name = "SamsungRadio"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"

[Lightroom]
enabled = false
app-name = "Lightroom"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "revanced/revanced-patches"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[Music-Extended]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Extended]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"

[YouTube-Advanced]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[Music-Advanced]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Advanced]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"

[Spotify-Advanced]
enabled = false 
app-name = "Spotify"
build-mode = "apk"
arch = "all"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
# uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# apkmirror-durl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
archive-dlurl = "https://archive.org/download/geologically/apks/com.spotify.music"




